from .language_keyboard import language_keyboard
from .accept_rules_keyboard import accept_rules_keyboard
from .update_tariff_plan_keyboard import update_tariff_plan_keyboard
from .crypto_payment_keyboard import crypto_payment_keyboard
from .close_keyboard import close_keyboard
from .support_keyboard import support_keyboard
from .greeting_video_note_keyboard import greeting_video_note_keyboard
